import i18n from '../../../i18n';
import { Skill } from '../skill.type';

export const TRANSPORT_SKILLS: Skill[] = [
  {
    id: '22d96fa5-453f-4a2b-84bc-0e67d7590763',
    category: 'transport',
    name: i18n.t('skill.transport.bike'),
    linkedAttribute: 'reaction',
    description: i18n.t('skill.transport.bikeDescription'),
    specialization: [],
  },
  {
    id: '332825ef-1082-4fde-925f-1cbc6a378afe',
    category: 'transport',
    name: i18n.t('skill.transport.car'),
    linkedAttribute: 'reaction',
    description: i18n.t('skill.transport.carDescription'),
    specialization: [],
  },
  {
    id: 'd83c8d77-272e-4cde-a4d8-1b7636ed9954',
    category: 'transport',
    name: i18n.t('skill.transport.hoverCraft'),
    linkedAttribute: 'reaction',
    description: i18n.t('skill.transport.hoverCraftDescription'),
    specialization: [],
  },
  {
    id: 'b592462b-337a-4c59-a0c1-0827a3e29648',
    category: 'transport',
    name: i18n.t('skill.transport.aeroStat'),
    linkedAttribute: 'reaction',
    description: i18n.t('skill.transport.aeroStatDescription'),
    specialization: [],
  },
  {
    id: '63ad3402-bf09-4b1c-9635-3017d243de5f',
    category: 'transport',
    name: i18n.t('skill.transport.motorBoat'),
    linkedAttribute: 'reaction',
    description: i18n.t('skill.transport.motorBoatDescription'),
    specialization: [],
  },
  {
    id: '721059c3-d39b-4e48-88c4-83133efafa84',
    category: 'transport',
    name: i18n.t('skill.transport.rotorCraft'),
    linkedAttribute: 'reaction',
    description: i18n.t('skill.transport.rotorCraftDescription'),
    specialization: [],
  },
  {
    id: 'd8587570-870f-461d-9453-2b345149caed',
    category: 'transport',
    name: i18n.t('skill.transport.sailboat'),
    linkedAttribute: 'reaction',
    description: i18n.t('skill.transport.sailboatDescription'),
    specialization: [],
  },
  {
    id: '7fa0e1bf-8075-4a74-9b11-892ef493ee21',
    category: 'transport',
    name: i18n.t('skill.transport.boat'),
    linkedAttribute: 'reaction',
    description: i18n.t('skill.transport.boatDescription'),
    specialization: [],
  },
  {
    id: 'fa7ba461-bf86-4ee8-b670-3936c96103f1',
    category: 'transport',
    name: i18n.t('skill.transport.submarine'),
    linkedAttribute: 'reaction',
    description: i18n.t('skill.transport.submarineDescription'),
    specialization: [],
  },
  {
    id: 'bed6b2ff-a943-4550-b0c2-9f67bca171d7',
    category: 'transport',
    name: i18n.t('skill.transport.verticalHelicopter'),
    linkedAttribute: 'reaction',
    description: i18n.t('skill.transport.verticalHelicopterDescription'),
    specialization: [],
  },
  {
    id: 'c23532d1-9af5-4745-ae46-ed5c48ffd32c',
    category: 'transport',
    name: i18n.t('skill.transport.plane'),
    linkedAttribute: 'reaction',
    description: i18n.t('skill.transport.planeDescription'),
    specialization: [],
  },
];
