import i18n from '../../../../i18n';
import { Weapon } from '../../weapon.type';

export const STEEL_ARMS_WEAPONS: Weapon[] = [
  {
    id: 'd6b36361-86fe-47ff-9026-9e1a6a89fc87',
    type: 'personal',
    name: i18n.t('weapon.personal.stabbingTip'),
    hiding: 12,
    reachLevel: 0,
    damage: {
      rating: 'strength',
      level: 'small',
      modifier: 2,
    },
    availability: null,
    price: null,
    streetCoefficient: null,
  },
  {
    id: '22b94b7d-97a8-4530-8559-c433c32f01d5',
    type: 'personal',
    name: i18n.t('bladeForForearms'),
    hiding: 7,
    reachLevel: 0,
    damage: {
      rating: 'strength',
      level: 'moderate',
    },
    weight: 1.5,
    availability: [4, { value: 48, dateType: 'hours' }],
    price: 850,
    streetCoefficient: 2,
  },
  {
    id: '98f4c15d-e6be-4f07-826d-9a8f23e17cec',
    type: 'personal',
    name: i18n.t('weapon.personal.katana'),
    hiding: 3,
    reachLevel: 1,
    damage: {
      rating: 'strength',
      level: 'moderate',
      modifier: 3,
    },
    weight: 1,
    availability: [4, { value: 48, dateType: 'hours' }],
    price: 1000,
    streetCoefficient: 2,
  },
  {
    id: 'd1090224-98e4-4598-a515-6a9380f43630',
    type: 'personal',
    name: i18n.t('weapon.personal.knife'),
    hiding: 8,
    reachLevel: null,
    damage: {
      rating: 'strength',
      level: 'small',
    },
    weight: 0.5,
    availability: [2, { value: 4, dateType: 'hours' }],
    price: 30,
    streetCoefficient: 0.75,
  },
  {
    id: '615e0d9c-fc7e-4d09-b62b-4e965a017b24',
    type: 'personal',
    name: i18n.t('weapon.personal.sword'),
    hiding: 4,
    reachLevel: 1,
    damage: {
      rating: 'strength',
      level: 'moderate',
      modifier: 2,
    },
    weight: 1,
    availability: [3, { value: 24, dateType: 'hours' }],
    price: 500,
    streetCoefficient: 1,
  },
  {
    id: '49550bc9-e929-4104-acd4-dfec4820e275',
    type: 'personal',
    name: i18n.t('weapon.personal.knifeOfSurvivor'),
    hiding: 6,
    reachLevel: 0,
    damage: {
      rating: 'strength',
      level: 'small',
    },
    weight: 0.75,
    availability: [3, { value: 6, dateType: 'hours' }],
    price: 450,
    streetCoefficient: 1,
  },
];
